const pokemon_id = {
    "bulbasaur": 1,
    "yvysaur": 2,
    "venusaur" : 3,
    "charmander" : 4
}
const pokemons = [
    {
        ID: 1,
        nome: "bulbasaur",
        nivel: 1,
        tipo: ["Planta", "Veneno"],
        tamanho: 0.7,
        peso: 6.9,
        sobre: "Possui um bulbo nas costas que armazena energia solar e cresce à medida que o Pokémon evolui. É conhecido por ser dócil e fiel, sendo uma escolha equilibrada para treinadores iniciantes.",
        fraqueza: ["fogo","gelo", "psiquico", "voador"],
        hab_principal: "Overgrow (Espessura)",
        hab_oculta: "Chlorophyll (Clorofila)",
        evolucoes: ["Ivysaur", "Venusaur"],
        imagem: "./Pokemons_Sprites/1_Bulbasaur.gif"
    },
    {
        ID: 2,
        nome: "ivysaur",
        nivel:16,
        tipo: ["Planta", "Veneno"],
        tamanho: 1,
        peso: 13,
        sobre: "Quando o bulbo em suas costas floresce, ele perde a capacidade de ficar em pé nas patas traseiras. Ele emite um aroma doce quando está prestes a desabrochar.",
        fraqueza: ["fogo","gelo", "psiquico", "voador"],
        hab_principal: "Overgrow (Espessura)",
        hab_oculta: "Chlorophyll (Clorofila)",
        evolucoes: ["bulbasaur", "venusaur"],
        imagem: "./Pokemons_Sprites/2_Ivysaur.gif"
    },
        {
        ID: 3,
        nome: "venusaur",
        nivel: 32,
        tipo: ["Planta", "Veneno"],
        tamanho: 2,
        peso: 100,
        sobre: "A flor em suas costas libera um aroma relaxante que acalma as emoções das pessoas e atrai outros Pokémon. Ela se torna mais vívida quando absorve muita energia solar.",
        fraqueza: ["fogo","gelo", "psiquico", "voador"],
        hab_principal: "Overgrow (Espessura)",
        hab_oculta: "Chlorophyll (Clorofila)",
        evolucoes: ["bulbasaur", "ivysaur"],
        imagem: "./Pokemons_Sprites/3_Venusaur.gif"
    },
    {
        ID: 4,
        nome: "charmander",
        nivel: 1,
        tipo: ["Fogo"],
        tamanho: 0.6,
        peso: 8.5,
        sobre: "A chama na ponta de sua cauda indica suas emoções. Se ele estiver alegre, a chama oscila; se estiver furioso, a chama queima intensamente. Se a chama se apagar, ele morre.",
        fraqueza: ["agua", "terra", "rocha"],
        hab_principal: "Blaze",
        hab_oculta: "Solar Power",
        evolucoes: ["charmeleon", "charizard"],
        imagem: "./Pokemons_Sprites/4_Charmander.gif"
    },
    {
        ID: 5,
        nome: "charmeleon",
        nivel: 16,
        tipo: ["Fogo"],
        tamanho: 1.1,
        peso: 19,
        sobre: "Tem uma natureza bárbara e adora lutas. Quando encontra um oponente forte, ele se torna agressivo e a chama na ponta de sua cauda queima com uma cor azul-esbranquiçada.",
        fraqueza: ["agua", "terra", "rocha"],
        hab_principal: "Blaze",
        hab_oculta: "Solar Power",
        evolucoes: ["charmander", "charizard"],
        imagem: "./Pokemons_Sprites/5_Charmeleon.gif"
    },
    {
        ID: 6,
        nome: "charizard",
        nivel: 36,
        tipo: ["fogo", "voador"],
        tamanho: 1.7,
        peso: 90.5,
        sobre: "Ele voa pelo céu em busca de oponentes poderosos. Cospe fogo com um calor tão intenso que é capaz de derreter rochas, mas nunca sopra chamas em um oponente mais fraco que ele.",
        fraqueza: ["eletrico", "agua", "rocha"],
        hab_principal: "Blaze",
        hab_oculta: "Solar Power",
        evolucoes: ["charmander", "charmeleon"],
        imagem: "./Pokemons_Sprites/6_Charizard.gif"
    },
]